export const dummyFoodList = [
    { id: "1", foodItemName: "Chicken Biryani", imageSource: "https://foodish-api.com/images/biryani/biryani42.jpg" },
    { id: "2", foodItemName: "Mutton Biryani", imageSource: "https://foodish-api.com/images/biryani/biryani68.jpg" },
    { id: "3", foodItemName: "Veg Biryani", imageSource: "https://foodish-api.com/images/biryani/biryani22.jpg" },
    { id: "4", foodItemName: "Cheese Burger", imageSource: "https://foodish-api.com/images/burger/burger19.jpg" },
    { id: "5", foodItemName: "Kebab Burger", imageSource: "https://foodish-api.com/images/burger/burger33.jpg" },
    { id: "6", foodItemName: "Double Patty Burger", imageSource: "https://foodish-api.com/images/burger/burger51.jpg" },
    { id: "7", foodItemName: "Classic Butter Chicken", imageSource: "https://foodish-api.com/images/butter-chicken/butter-chicken14.jpg" },
    { id: "8", foodItemName: "Spicy Butter Chicken", imageSource: "https://foodish-api.com/images/butter-chicken/butter-chicken4.jpg" },
    { id: "9", foodItemName: "Butter Chicken Masala", imageSource: "https://foodish-api.com/images/butter-chicken/butter-chicken11.jpg" },
    { id: "10", foodItemName: "Chocolate Dessert", imageSource: "https://foodish-api.com/images/dessert/dessert7.jpg" },
    { id: "11", foodItemName: "Fruit Dessert", imageSource: "https://foodish-api.com/images/dessert/dessert29.jpg" },
    { id: "12", foodItemName: "Pastry Dessert", imageSource: "https://foodish-api.com/images/dessert/dessert15.jpg" },
    { id: "13", foodItemName: "Plain Dosa", imageSource: "https://foodish-api.com/images/dosa/dosa54.jpg" },
    { id: "14", foodItemName: "Masala Dosa", imageSource: "https://foodish-api.com/images/dosa/dosa3.jpg" },
    { id: "15", foodItemName: "Cheese Dosa", imageSource: "https://foodish-api.com/images/dosa/dosa48.jpg" },
    { id: "16", foodItemName: "Sambhar Idly", imageSource: "https://foodish-api.com/images/idly/idly20.jpg" },
    { id: "17", foodItemName: "Fried Idly", imageSource: "https://foodish-api.com/images/idly/idly50.jpg" },
    { id: "18", foodItemName: "Cheese Idly", imageSource: "https://foodish-api.com/images/idly/idly8.jpg" },
    { id: "19", foodItemName: "Penne Pasta", imageSource: "https://foodish-api.com/images/pasta/pasta12.jpg" },
    { id: "20", foodItemName: "Spaghetti Pasta", imageSource: "https://foodish-api.com/images/pasta/pasta27.jpg" },
    { id: "21", foodItemName: "Macaroni Pasta", imageSource: "https://foodish-api.com/images/pasta/pasta5.jpg" },
    { id: "22", foodItemName: "Margherita Pizza", imageSource: "https://foodish-api.com/images/pizza/pizza65.jpg" },
    { id: "23", foodItemName: "Pepperoni Pizza", imageSource: "https://foodish-api.com/images/pizza/pizza15.jpg" },
    { id: "24", foodItemName: "BBQ Chicken Pizza", imageSource: "https://foodish-api.com/images/pizza/pizza47.jpg" },
    { id: "25", foodItemName: "Steamed Rice", imageSource: "https://foodish-api.com/images/rice/rice11.jpg" },
    { id: "26", foodItemName: "Fried Rice", imageSource: "https://foodish-api.com/images/rice/rice30.jpg" },
    { id: "27", foodItemName: "Jeera Rice", imageSource: "https://foodish-api.com/images/rice/rice17.jpg" },
    { id: "28", foodItemName: "Samosa", imageSource: "https://foodish-api.com/images/samosa/samosa10.jpg" },
    { id: "29", foodItemName: "Paneer Tikka Samosa", imageSource: "https://foodish-api.com/images/samosa/samosa5.jpg" },
    { id: "30", foodItemName: "Veg Burger", imageSource: "https://foodish-api.com/images/burger/burger77.jpg" },
    { id: "31", foodItemName: "Grilled Chicken Burger", imageSource: "https://foodish-api.com/images/burger/burger61.jpg" },
    { id: "32", foodItemName: "Butter Paneer", imageSource: "https://foodish-api.com/images/butter-chicken/butter-chicken6.jpg" },
    { id: "33", foodItemName: "Butter Chicken Tikka", imageSource: "https://foodish-api.com/images/butter-chicken/butter-chicken19.jpg" },
    { id: "34", foodItemName: "Ice Cream Dessert", imageSource: "https://foodish-api.com/images/dessert/dessert9.jpg" },
    { id: "35", foodItemName: "Ghee Roast Dosa", imageSource: "https://foodish-api.com/images/dosa/dosa61.jpg" },
    { id: "36", foodItemName: "Stuffed Masala Dosa", imageSource: "https://foodish-api.com/images/dosa/dosa71.jpg" },
    { id: "37", foodItemName: "Rava Dosa", imageSource: "https://foodish-api.com/images/dosa/dosa48.jpg" },
    { id: "38", foodItemName: "Mini Idly", imageSource: "https://foodish-api.com/images/idly/idly31.jpg" },
    { id: "39", foodItemName: "Pasta Arrabbiata", imageSource: "https://foodish-api.com/images/pasta/pasta23.jpg" },
    { id: "40", foodItemName: "Alfredo Pasta", imageSource: "https://foodish-api.com/images/pasta/pasta8.jpg" },
    { id: "41", foodItemName: "Tandoori Paneer Pizza", imageSource: "https://foodish-api.com/images/pizza/pizza89.jpg" },
    { id: "42", foodItemName: "Garlic Bread Pizza", imageSource: "https://foodish-api.com/images/pizza/pizza37.jpg" },
    { id: "43", foodItemName: "Lemon Rice", imageSource: "https://foodish-api.com/images/rice/rice6.jpg" },
    { id: "44", foodItemName: "Egg Fried Rice", imageSource: "https://foodish-api.com/images/rice/rice13.jpg" },
    { id: "45", foodItemName: "Onion Samosa", imageSource: "https://foodish-api.com/images/samosa/samosa3.jpg" },
    { id: "46", foodItemName: "Veggie Biryani", imageSource: "https://foodish-api.com/images/biryani/biryani33.jpg" },
    { id: "47", foodItemName: "Mushroom Burger", imageSource: "https://foodish-api.com/images/burger/burger77.jpg" },
    { id: "48", foodItemName: "Classic Spaghetti", imageSource: "https://foodish-api.com/images/pasta/pasta27.jpg" },
    { id: "49", foodItemName: "Paneer Tikka Pizza", imageSource: "https://foodish-api.com/images/pizza/pizza47.jpg" },
    { id: "50", foodItemName: "Chettinad Biryani", imageSource: "https://foodish-api.com/images/biryani/biryani55.jpg" }
];
